apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-giqz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-giqz@sha256:d3a07d807ccc1d63944768bd29823cecd183c43e46ff27a75b3cccf42d81ee9b
        name: my-nodejs
        resources: {}
status: {}
